apiVersion: v1
kind: Secret
metadata:
  name: github-runner-secrets
type: Opaque
stringData:
  RUNNER_URL: "https://github.com/ashishkumar256/terrateam-demo"
  RUNNER_TOKEN: "<YOUR_TOKEN>"
  RUNNER_NAME: "infra"
  RUNNER_GROUP: "Default"
  RUNNER_LABELS: "infra"
  RUNNER_WORKDIR: "/opt/github-runner/"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-runner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: github-runner
  template:
    metadata:
      labels:
        app: github-runner
    spec:
      containers:
      - name: runner
        image: ashishkumar256/github-runner:latest 
        envFrom:
        - secretRef:
            name: github-runner-secrets
        volumeMounts:
        - name: runner-work
          mountPath: /opt/github-runner/
      volumes:
      - name: runner-work
        emptyDir: {}
