apiVersion: v1
kind: Namespace
metadata:
  name: github
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: github-runner
  namespace: github
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: github-runner
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log", "services", "endpoints", "configmaps"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets", "daemonsets", "replicasets"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]
  - apiGroups: ["batch"]
    resources: ["jobs", "cronjobs"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["roles", "rolebindings"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: github-runner-binding
subjects:
  - kind: ServiceAccount
    name: github-runner
    namespace: github 
roleRef:
  kind: ClusterRole
  name: github-runner
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Secret
metadata:
  name: github-runner-secrets
type: Opaque
stringData:
  RUNNER_URL: "https://github.com/ashishkumar256/terrateam-demo"
  RUNNER_TOKEN: "<YOUR_TOKEN>"
  RUNNER_NAME: "infra"
  RUNNER_GROUP: "Default"
  RUNNER_LABELS: "infra"
  RUNNER_WORKDIR: "/opt/github-runner/"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-runner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: github-runner
  template:
    metadata:
      labels:
        app: github-runner
    spec:
      serviceAccountName: github-runner
      containers:
      - name: runner
        image: ashishkumar256/github-runner:latest 
        envFrom:
        - secretRef:
            name: github-runner-secrets
        volumeMounts:
        - name: runner-work
          mountPath: /opt/github-runner/
      volumes:
      - name: runner-work
        emptyDir: {}
